# Generated by Django 3.0.3 on 2020-07-17 14:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('data', models.DateField(auto_now=True)),
                ('title', models.CharField(max_length=40)),
                ('text', models.TextField()),
                ('idtag', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samplegraph.Categories')),
            ],
        ),
    ]
