# Generated by Django 3.0.3 on 2020-07-17 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samplegraph', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='data',
            new_name='date',
        ),
    ]
